branch-defaults:
  main:
    environment: nicowell-app
    group_suffix: null
global:
  application_name: nicowell
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ${AWS_REGION}
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application