version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nicowell-backend"
# s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "nicowell-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []