version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nicowell-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-${AWS::AccountId}"
s3_prefix = "nicowell-backend"
region = "${env:AWS_REGION}"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "OpenAIApiKey=\"${env:OPENAI_API_KEY}\""
image_repositories = []