branch-defaults:
  main:
    environment: nicowell-app
    group_suffix: null
global:
  application_name: nicowell
  branch: main
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application